# Generated by Django 2.1.5 on 2019-02-06 02:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markparent',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 0, 0, tzinfo=utc), editable=False),
        ),
        migrations.AddField(
            model_name='markparent',
            name='modified_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 6, 0, 0, tzinfo=utc)),
        ),
    ]
